### ISSUE TITLE
Is client secret readable ?

### ISSUE THREAD

**Issue by talhakosen** [stripe-samples/firebase-mobile-payments#2]
https://github.com/stripe-samples/firebase-mobile-payments/blob/d114070ebcd4ca1a538bf7f336c0e506afab64ce/android/app/src/main/java/com/example/firebasemobilepayments/MainActivity.kt#L85

**Comment by thorsten-stripe** [comment]
![image](https://user-images.githubusercontent.com/23213994/109944379-2266a380-7d11-11eb-9fa9-739b22cbfba1.png)
https://stripe.com/docs/api/payment_intents/object#payment_intent_object-client_secret

**Comment by talhakosen** [comment]
sorry, i assumed client_secret as secret_key. You are right i have same approach on my app too. Thank you for the answer!
