### ISSUE TITLE
iOS Coming Soon

### ISSUE THREAD

**Issue by operatordevelopment** [stripe-samples/firebase-mobile-payments#3]
# Bug report

## Describe the bug
README file indicates iOS is coming soon.  Last commit was 7 months ago.

Wondering if there is a pre-release version in the works?

Or maybe the plan to add iOS changed because there was something already available?  Maybe I am looking in the wrong place?

Thank you in advance!
Del

**Comment by thorsten-stripe** [comment]
@operatordevelopment yes, sorry about that, we were waiting for our new payments ui feature: https://stripe.com/docs/mobile/payments-ui-beta

I've added an iOS example now.

**Comment by operatordevelopment** [comment]
Thanks so much @thorsten-stripe .  I'm looking at the iOS example now.
